### ISSUE TITLE
Type stubs not found for chatlas

### ISSUE THREAD

**Issue by wch** [posit-dev/chatlas#51]
Pyright is not able to find the type stubs for chatlas when installed from PyPI.

![Image](https://github.com/user-attachments/assets/0b9c95c1-b718-41b1-974f-08281785a910)

I think it needs a py.typed file.

**Comment by cpsievert** [comment]
Seems [5c846fa](https://github.com/posit-dev/chatlas/commit/5c846fa0c23a90c6f43a3923ab755efe5873ed10) should fix it, but I'm not positive. Would it be possible to confirm prior to PyPI release?

**Comment by wch** [comment]
I think if you build a wheel and install it, that's sufficient for testing. (Or `pip install` from github.)

**Comment by wch** [comment]
Update: I just installed from github and still see the problem.

Note that this is from the installation output:
```
Successfully installed chatlas-0.3.1.dev11+g5c846fa
```

**Comment by wch** [comment]
I think maybe you need to commit the py.typed file?

**Comment by cpsievert** [comment]
Ah yea, just pushed that

**Comment by wch** [comment]
Now it can find type stubs for chatlas, but it says the type for `ChatAnthropic` is partially unknown:

<img width="1068" alt="Image" src="https://github.com/user-attachments/assets/44057a45-86d1-4af3-a6eb-8f813ab0e158" />

I think the problem is that `Turn` is generic and needs a type here, as in `Turn[str]` (although `str` is not the right type here):

https://github.com/posit-dev/chatlas/blob/90727ffa8786210211d6d8c5b718649f81642120/chatlas/_anthropic.py#L57

**Comment by cpsievert** [comment]
Oh shoot, I don't have `"typeCheckingMode": "strict"` setup. Started a new issue in https://github.com/posit-dev/chatlas/issues/53

**Comment by wch** [comment]
Interestingly, when I clone the repo and look at it locally, I see different type-checking issues. The `Turn` thing doesn't raise any issues, but it complains about `ag_frame` and `gi_frame` in _chat.py.

**Comment by cpsievert** [comment]
Yea, I had just noticed that too. aeaa3b88ca344b85e27b05bcbfecda53c1b45e2d fixes it
